name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  matrix-prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v4
    - id: set-matrix
      run: |
        echo "matrix=$(cat .github/matrix/c-shared-build.json | jq -c '.')" >> $GITHUB_OUTPUT

  c-shared-builds:
    needs: matrix-prep
    strategy:
      matrix: ${{ fromJson(needs.matrix-prep.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/c-shared-build
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  c-shared-release:
    needs: c-shared-builds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/c-shared-release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}